[package]
name = "bounce"
version = "0.0.1"
authors = ["owen <owen@oms.sh>"]
license = "AGPL"

[dependencies]
bytes = "0.4.2"
futures = "0.1.13"
tokio-io = "0.1.1"
tokio-core = "0.1.6"
tokio-timer = "0.1.1"
time = "0.1.37"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
toml = "*"

